security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            anonymous: true
            lazy: true
            stateless: true # Authentification demandée à chaque requête
            json_login:
                check_path: api_login
            pattern: ^/api/
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login

    access_control:
        - { path: ^/(en|fr|pl|it)/$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/home$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/forgot_password, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/new_password, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/validate_account, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/search, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/admin/get_, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/admin, roles: [ ROLE_ADMIN, ROLE_SUPER_ADMIN ], requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/api/forgot_password$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/api/signup$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/apip/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/api/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/api/validate_account, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/api, roles: ROLE_USER, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/, roles: ROLE_USER, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/account$, roles: ROLE_USER, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/institution$, roles: ROLE_INSTITUTION, requires_channel: '%router.request_context.scheme%' }
        - { path: ^/(en|fr|pl|it)/recruiter$, roles: ROLE_RECRUITER, requires_channel: '%router.request_context.scheme%' }

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_MODERATOR
        ROLE_MODERATOR: ROLE_USER
        ROLE_INSTITUTION: ROLE_USER
        ROLE_RECRUITER: ROLE_RECRUITER
